// DATA
export const QUERY_DYNAMO_DB = 'QUERY_DYNAMO_DB';
export const QUERY_DYNAMO_DB_SUCCESS = 'QUERY_DYNAMO_DB_SUCCESS';
export const QUERY_RDS = 'QUERY_RDS';
export const QUERY_RDS_SUCCESS = 'QUERY_RDS_SUCCESS';